version: "3"

services:
  ansible:
    container_name: ansible_host
    build:
      context: ./ansible/
      args:
        ENV_ANSIBLE_PORT: ${ENV_ANSIBLE_PORT}
        ENV_ANSIBLE_CLIENT_PORT: ${ENV_ANSIBLE_CLIENT_PORT}
        ENV_ANSIBLE_VERSION: ${ENV_ANSIBLE_VERSION}
        ENV_ANSIBLE_LINT_VERSION: ${ENV_ANSIBLE_LINT_VERSION}
    image: ansible_host
    restart: always
    env_file: 
      - ./.env
    ports:
      - ${ENV_ANSIBLE_PORT}:80
    # links:
    #   - client
    # volumes:
    #   - ../project/${ENV_SRC_DIRECTORY}:${ENV_DOUCMENT_ROOT}/${ENV_SRC_DIRECTORY}
    stdin_open: true
    tty: true
    # privileged: true
    environment: 
      TZ: Asia/Tokyo
    networks:
      - ansible_net

  client:
    container_name: ansible_client
    build: ./client/
    image: ansible_client
    # restart: always
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - ${ENV_ANSIBLE_CLIENT_PORT}:8000
    depends_on:
      - ansible
    networks:
      - ansible_net

networks:
  ansible_net:
    driver: bridge